name: Deploy and Setup VPN

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name:  Use Node.js
        uses: actions/setup-node@v3  
        with:
          node-version: '21.6.1'  

      - name: Install Dependencies
        run: npm install --prefix weather


      - name: Build React App
        run: npm run build --prefix weather